import type { SectionType } from '../types';

/**
 * Section Type Configuration
 * Defines which options and features are available for each section type
 */
export interface SectionTypeConfig {
  // Content options
  supportsTitle: boolean;
  supportsSubtitle: boolean;
  supportsRichText: boolean;
  supportsItems: boolean;
  supportsSingleImage: boolean;
  supportsMultipleImages: boolean;
  
  // Layout options
  supportedLayouts: string[];
  defaultLayout: string;
  
  // Special features
  supportsCTA: boolean;
  supportsForm: boolean;
  supportsVideo: boolean;
  supportsMap: boolean;
  supportsStatistics: boolean;
  supportsTimeline: boolean;
  supportsFAQ: boolean;
  supportsTestimonials: boolean;
  
  // Design options
  supportsBackground: boolean;
  supportsSpacing: boolean;
  supportsAnimation: boolean;
  
  // Item-specific options
  itemSupportsImage: boolean;
  itemSupportsLink: boolean;
  itemSupportsIcon: boolean;
  itemSupportsValue: boolean;
  itemSupportsRating: boolean;
}

/**
 * Configuration map for each section type
 */
export const SECTION_TYPE_CONFIG: Record<SectionType, SectionTypeConfig> = {
  // Hero & Banner
  HERO_BANNER: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: false,
    supportsSingleImage: true,
    supportsMultipleImages: false,
    supportedLayouts: ['FULL_WIDTH', 'CONTAINED'],
    defaultLayout: 'FULL_WIDTH',
    supportsCTA: true,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  // Content Sections
  PARAGRAPH_CONTENT: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: true,
    supportsItems: false,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['CONTAINED', 'FULL_WIDTH'],
    defaultLayout: 'CONTAINED',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  IMAGE_WITH_TEXT: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: true,
    supportsItems: false,
    supportsSingleImage: true,
    supportsMultipleImages: false,
    supportedLayouts: ['SPLIT', 'CONTAINED', 'FULL_WIDTH'],
    defaultLayout: 'SPLIT',
    supportsCTA: true,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  SPLIT_CONTENT: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: true,
    supportsItems: false,
    supportsSingleImage: true,
    supportsMultipleImages: false,
    supportedLayouts: ['SPLIT'],
    defaultLayout: 'SPLIT',
    supportsCTA: true,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  // Media Sections
  IMAGE_GALLERY: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: true,
    supportedLayouts: ['GRID', 'MASONRY', 'CAROUSEL', 'SCROLLING_ROW'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  VIDEO_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: false,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['CONTAINED', 'FULL_WIDTH'],
    defaultLayout: 'CONTAINED',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: true,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  // Card & Grid Sections
  CARD_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'ROW', 'SCROLLING_ROW', 'CAROUSEL', 'MASONRY'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  FEATURES_GRID: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'ROW', 'SCROLLING_ROW'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: true,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  STATISTICS_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'ROW', 'SCROLLING_ROW'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: true,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: true,
    itemSupportsValue: true,
    itemSupportsRating: false,
  },
  
  TEAM_MEMBERS: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'ROW', 'SCROLLING_ROW', 'CAROUSEL'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  // Interactive Sections
  FAQ_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['LIST', 'CONTAINED'],
    defaultLayout: 'LIST',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: true,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  FORM_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: false,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['CONTAINED', 'FULL_WIDTH'],
    defaultLayout: 'CONTAINED',
    supportsCTA: false,
    supportsForm: true,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  TESTIMONIALS_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'CAROUSEL', 'SCROLLING_ROW'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: true,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: true,
  },
  
  TIMELINE_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['LIST', 'CONTAINED'],
    defaultLayout: 'LIST',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: true,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  // Specialized Sections
  NEWS_FEED: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'LIST', 'SCROLLING_ROW', 'CAROUSEL'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  SCHEMES_LIST: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'LIST', 'SCROLLING_ROW'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: false,
    itemSupportsValue: true,
    itemSupportsRating: false,
  },
  
  CONTACT_INFO: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'LIST', 'SPLIT'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: true,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: true,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  MAP_SECTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: false,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['FULL_WIDTH', 'CONTAINED'],
    defaultLayout: 'FULL_WIDTH',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: true,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  CALL_TO_ACTION: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: true,
    supportsItems: false,
    supportsSingleImage: true,
    supportsMultipleImages: false,
    supportedLayouts: ['CONTAINED', 'FULL_WIDTH'],
    defaultLayout: 'CONTAINED',
    supportsCTA: true,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: false,
    itemSupportsLink: false,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
  
  ACTIVE_PANCHAYATS_GRID: {
    supportsTitle: true,
    supportsSubtitle: true,
    supportsRichText: false,
    supportsItems: true,
    supportsSingleImage: false,
    supportsMultipleImages: false,
    supportedLayouts: ['GRID', 'ROW', 'SCROLLING_ROW', 'CAROUSEL'],
    defaultLayout: 'GRID',
    supportsCTA: false,
    supportsForm: false,
    supportsVideo: false,
    supportsMap: false,
    supportsStatistics: false,
    supportsTimeline: false,
    supportsFAQ: false,
    supportsTestimonials: false,
    supportsBackground: true,
    supportsSpacing: true,
    supportsAnimation: true,
    itemSupportsImage: true,
    itemSupportsLink: true,
    itemSupportsIcon: false,
    itemSupportsValue: false,
    itemSupportsRating: false,
  },
};

/**
 * Get configuration for a section type
 */
export function getSectionTypeConfig(type: SectionType | string): SectionTypeConfig {
  return SECTION_TYPE_CONFIG[type as SectionType] || SECTION_TYPE_CONFIG.CARD_SECTION;
}

/**
 * Map old section types to new professional types for backward compatibility
 */
export function mapOldSectionType(oldType: string): SectionType {
  const mapping: Record<string, SectionType> = {
    'HERO': 'HERO_BANNER',
    'STATS': 'STATISTICS_SECTION',
    'FEATURES': 'FEATURES_GRID',
    'ACTIVE_PANCHAYATS': 'ACTIVE_PANCHAYATS_GRID',
    'NEWS': 'NEWS_FEED',
    'ANNOUNCEMENTS': 'NEWS_FEED',
    'CTA': 'CALL_TO_ACTION',
    'GALLERY': 'IMAGE_GALLERY',
    'CARDS': 'CARD_SECTION',
    'FAQ': 'FAQ_SECTION',
    'FORM': 'FORM_SECTION',
    'VIDEO': 'VIDEO_SECTION',
    'TIMELINE': 'TIMELINE_SECTION',
    'TESTIMONIALS': 'TESTIMONIALS_SECTION',
    'RICH_TEXT': 'PARAGRAPH_CONTENT',
    'MAP': 'MAP_SECTION',
    'SCHEMES': 'SCHEMES_LIST',
    'MEMBERS': 'TEAM_MEMBERS',
    'CONTACT': 'CONTACT_INFO',
  };
  
  return mapping[oldType] || (oldType as SectionType) || 'CARD_SECTION';
}

/**
 * Map new professional section types back to legacy types for backend compatibility
 * This ensures backward compatibility when saving to backend
 */
export function mapToBackendSectionType(frontendType: string): string {
  // If it's already a legacy type, return as is
  const legacyTypes = [
    'HERO', 'STATS', 'FEATURES', 'ACTIVE_PANCHAYATS', 'NEWS', 'CTA',
    'ANNOUNCEMENTS', 'SCHEMES', 'MEMBERS', 'CONTACT', 'GALLERY', 'CARDS',
    'FAQ', 'FORM', 'VIDEO', 'TIMELINE', 'TESTIMONIALS', 'RICH_TEXT', 'MAP'
  ];
  
  if (legacyTypes.includes(frontendType)) {
    return frontendType;
  }
  
  // Map new types to legacy types
  const reverseMapping: Record<string, string> = {
    'HERO_BANNER': 'HERO',
    'STATISTICS_SECTION': 'STATS',
    'FEATURES_GRID': 'FEATURES',
    'ACTIVE_PANCHAYATS_GRID': 'ACTIVE_PANCHAYATS',
    'NEWS_FEED': 'NEWS',
    'CALL_TO_ACTION': 'CTA',
    'IMAGE_GALLERY': 'GALLERY',
    'CARD_SECTION': 'CARDS',
    'FAQ_SECTION': 'FAQ',
    'FORM_SECTION': 'FORM',
    'VIDEO_SECTION': 'VIDEO',
    'TIMELINE_SECTION': 'TIMELINE',
    'TESTIMONIALS_SECTION': 'TESTIMONIALS',
    'PARAGRAPH_CONTENT': 'RICH_TEXT',
    'MAP_SECTION': 'MAP',
    'SCHEMES_LIST': 'SCHEMES',
    'TEAM_MEMBERS': 'MEMBERS',
    'CONTACT_INFO': 'CONTACT',
    // Keep new types that don't have legacy equivalents
    'IMAGE_WITH_TEXT': 'IMAGE_WITH_TEXT',
    'SPLIT_CONTENT': 'SPLIT_CONTENT',
  };
  
  return reverseMapping[frontendType] || frontendType;
}

